---
- name: (Web) DNF Upgrade all packages Centos 9
  ansible.builtin.dnf:
    name: '*'
    state: latest

- name: (Web) Install nginx
  become: yes
  shell: |
    yes | sudo dnf install nginx
    sudo systemctl enable nginx
  notify:
    - Reload nginx

- name: Remove default site config
  file: path="/etc/nginx/nginx.conf" state=absent
  notify:
    - Reload nginx
#
#- name: Remove default site
#  file: path="/usr/share/nginx/html" state=absent
#  tags: nginx_config
#  notify:
#    - Reload nginx
#
- name: Install nginx config
  template: src="nginx.conf" dest="/etc/nginx/nginx.conf"
  become: yes
  notify:
    - Reload nginx






